networks:
  dev:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/database/app.db:/database/app.db
    networks:
      - dev 

  frontend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.server
    networks:
      - dev 
      
  nginx:
    build:
      context: .
      dockerfile: .docker/Dockerfile.server
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - dev 

