FROM node:18 as frontend

COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install

COPY ./frontend .

RUN npm run build


FROM nginx:alpine as nginx

COPY ./server/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend ./dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
